AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31  # Enables SAM simplifications for serverless apps
Description: Lambda contact API for portfolio
Resources:                             # Must exist; top-level section required by SAM
  ContactFunction:
    Type: AWS::Serverless::Function  # Defines a Lambda function
    Properties:
      CodeUri: ./                     # Path to Lambda code
      Handler: lambda_function.lambda_handler # Lambda handler function
      Runtime: python3.11             # Runtime environment
      Environment:                    # Environment variables for SMTP
        Variables:
          SMTP_USER: "talktoitu@gmail.com"
          SMTP_PASS: "kalidas7183"
          TO_EMAIL: "talktoitu@gmail.com"
      Events:
        Api:                          # API Gateway trigger for Lambda
          Type: Api
          Properties:
            Path: /api/contact        # HTTP endpoint path
            Method: post              # HTTP method to trigger Lambda

      Outputs:
        ApiUrl:
          Description: "API Gateway endpoint URL"
          Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/contact"
