name: Deploy Portfolio
on:
  push:
    branches: [ development ]  # Trigger deployment on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout repo code

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.YOUR_REGION }}  # Replace with your AWS region

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18          # Node version for frontend build

      - name: Build Frontend
        run: |
          cd frontend
          npm ci                     # Install exact dependencies from package-lock.json
          npm run build              # Build production frontend

      - name: Upload to S3
        run: aws s3 sync frontend/dist s3://santosh-s3-bucket-demo --delete # Sync built files to S3

      - name: Deploy Lambda (SAM)
        run: |
          cd backend
          pip install aws-sam-cli    # Install SAM CLI
          sam build && sam deploy --no-confirm-changeset --stack-name santosh-portfolio-api --capabilities CAPABILITY_IAM # Build and deploy Lambda