name: CI-CD Demo

on:
  push:
    branches: [ "portfolio-site" ]
  pull_request:
    branches: [ "portfolio-site" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./  # <--- important since code is in subfolder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          npm install

  deploy-to-render:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/portfolio-site'   # 👈 ensure only from FastAPIDev
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
